// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayuollxegukienjqsdac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5dW9sbHhlZ3VraWVuanFzZGFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTM2NTMsImV4cCI6MjA1NjU4OTY1M30.mfSbnnqxBgufEgrzn9ptPqyIEPbQXa_EldJ0vKeznDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);